# Generated by Django 5.0.2 on 2024-02-24 06:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import main.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(verbose_name='Summa')),
            ],
            options={
                'verbose_name': 'Cassa',
                'verbose_name_plural': 'Hisob',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': "Bo'lim",
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('extra_info', models.TextField(verbose_name="Qo'shimcha malumotlar")),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Jihoz',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Summa')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Vaqti')),
                ('reason', models.TextField(verbose_name='Sababi')),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Daromat',
            },
        ),
        migrations.CreateModel(
            name='Info_about_clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_patients_number', models.IntegerField(verbose_name='Bemorlar soni')),
                ('total_employees_number', models.IntegerField(verbose_name='Xodimlar soni')),
                ('bio', models.TextField(verbose_name='Malumot')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Invalide phone number', regex='^[\\+]9{2}8{1}[0-9]{9}$')], verbose_name='Telefon Raqam')),
            ],
            options={
                'verbose_name': 'Info_about_clinic',
                'verbose_name_plural': 'Klinika malumotlari',
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Summa')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Vaqti')),
                ('reason', models.TextField(verbose_name='Sababi')),
            ],
            options={
                'verbose_name': 'Revenue',
                'verbose_name_plural': 'Xarajat',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Invalide phone number', regex='^[\\+]9{2}8{1}[0-9]{9}$')], verbose_name='Telefon Raqam')),
                ('address', models.TextField(verbose_name='Yashash manzil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Foydalanuvchilar',
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'doctor'), (2, 'manager'), (3, 'admin'), (4, 'nurse'), (5, 'director'), (6, 'cooker')], verbose_name='Lavozim')),
                ('age', models.IntegerField(verbose_name='Yosh')),
                ('salary', models.IntegerField(verbose_name='Oylik  maoshi')),
                ('work_time', models.TextField(verbose_name='Ish vaqti')),
                ('experience', models.IntegerField(verbose_name='Ish tajribasi')),
                ('bio', models.TextField(verbose_name='Malumotlari')),
                ('info_qr_code', models.ImageField(blank=True, null=True, upload_to='doctor_qr_codes/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department', verbose_name="Bo'limi")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Xodimlar',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='FIO')),
                ('age', models.IntegerField(verbose_name='Yosh')),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Invalide phone number', regex='^[\\+]9{2}8{1}[0-9]{9}$')], verbose_name='Telefon Raqami')),
                ('address', models.TextField(verbose_name='Yashash manzili')),
                ('photo', models.ImageField(upload_to='patient_photos', validators=[main.validators.ImageFileValidator])),
                ('extra_phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Invalide phone number', regex='^[\\+]9{2}8{1}[0-9]{9}$')], verbose_name='Telefon Raqami')),
                ('bio', models.TextField(verbose_name='Malumotlari')),
                ('booked_room_day', models.DateField(verbose_name='Mudati')),
                ('payment_status', models.IntegerField(choices=[(1, 'pay'), (2, 'pard_paid'), (3, 'unpaid')], default=3, verbose_name="To'lov xolati")),
                ('gender', models.IntegerField(choices=[(1, 'men'), (2, 'women')], verbose_name='Jinsi')),
                ('info_qr_code', models.ImageField(blank=True, null=True, upload_to='patient_qr_codes/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee', verbose_name='Shifokori')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Bemorlar',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'comment'), (2, 'camplain'), (3, 'suggestion')], default=1)),
                ('text', models.TextField(verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Vaqti')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Izoh',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.IntegerField(verbose_name='Tolov summasi')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Vaqti')),
                ('payment_type', models.IntegerField(choices=[(1, 'card'), (2, 'cash'), (3, 'other ')], verbose_name='Tolov turi')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='payment_qr_codes/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': "To'lov",
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('number', models.IntegerField(null=True)),
                ('capacity', models.IntegerField(verbose_name="Sig'imi")),
                ('status', models.IntegerField(choices=[(1, 'economic'), (2, 'semi-deluxe'), (3, 'deluxe'), (4, 'pro-deluxe'), (5, 'staff'), (6, 'operating')], verbose_name='Tarifi')),
                ('is_booked', models.BooleanField(blank=True, null=True, verbose_name='Bandligi')),
                ('other_info', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha malimotlar")),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department', verbose_name="Bo'limi")),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.equipment', verbose_name='Jihozlar')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Xona',
                'unique_together': {('number', 'department')},
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room', verbose_name='Xonasi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room', verbose_name='Xonasi'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
            options={
                'unique_together': {('employee', 'data')},
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Sana')),
                ('start_time', models.TimeField(verbose_name='Boshlangan vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('doctors', models.ManyToManyField(to='main.employee', verbose_name='Doctorlar')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient', verbose_name='Bemor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room', verbose_name='Xona')),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operatsiya',
                'unique_together': {('start_time', 'room')},
            },
        ),
    ]
