# Generated by Django 5.0.2 on 2024-02-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='narxi $'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('1', 'comment'), ('2', 'camplain'), ('3', 'suggestion'), ('comment', 'comment'), ('camplain', 'camplain'), ('suggestion', 'suggestion')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('1', 'doctor'), ('2', 'manager'), ('3', 'admin'), ('4', 'nurse'), ('5', 'director'), ('6', 'cooker'), ('doctor', 'doctor'), ('manager', 'manager'), ('admin', 'admin'), ('nurse', 'nurse'), ('director', 'director'), ('cooker', 'cooker')], verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('1', 'men'), ('2', 'women'), ('men', 'men'), ('women', 'women')], verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='payment_status',
            field=models.CharField(choices=[('1', 'pay'), ('2', 'pard_paid'), ('3', 'unpaid'), ('pay', 'pay'), ('pard_paid', 'pard_paid'), ('unpaid', 'unpaid')], default=3, verbose_name="To'lov xolati"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('1', 'card'), ('2', 'cash'), ('3', 'other '), ('card', 'card'), ('cash', 'cash'), ('other', 'other')], verbose_name='Tolov turi'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('1', 'economic'), ('2', 'semi-deluxe'), ('3', 'deluxe'), ('4', 'pro-deluxe'), ('5', 'staff'), ('6', 'operating'), ('economic', 'economic'), ('semi-deluxe', 'semi-deluxe'), ('deluxe', 'deluxe'), ('pro-deluxe', 'pro-deluxe'), ('staff', 'staff'), ('operating', 'operating')], verbose_name='Tarifi'),
        ),
    ]
